spring:
  application:
    name: configServer
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Sarah-hui/springcloudConfig/
          searchPaths: respo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/